mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.bfh.mycat.entity
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
    local-cache-scope: statement
  global-config:
    db-config:
      table-prefix: t_
      table-underline: true
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:8066/t?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
        format_sql: true
    show-sql: true

server:
  port: 8080

logging:
  file:
    name: log.txt
  level:
    com.bfh.mycat: debug
